Readme docs and delivery dockerhub (#9)
* readme + dockerhub delivery
* readme + front test coverage report as artifact
* SENDGRID_API_KEY from env + secret
* remove useless mailservice in front + improve ci

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -25,6 +25,8 @@ jobs:
         uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
 
       - name: Build with Gradle Wrapper
+        env:
+          SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
         run: chmod +x gradlew && ./gradlew build
         working-directory: ./backend
 
@@ -101,6 +103,8 @@ jobs:
         uses: docker/setup-buildx-action@v3
 
       - name: Build and run Docker Compose
+        env:
+          SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
         run: docker-compose up --build -d
         working-directory: .
 
@@ -113,32 +117,15 @@ jobs:
           done
         working-directory: .
 
-      - name: frontend service
-        run: |
-          success=false
-          for i in {1..10}; do
-            if curl -f http://localhost:4201; then
-              success=true
-              break
-            else
-              sleep 10
-            fi
-          done
-          
-          if [ "$success" = false ]; then
-            echo "Curl failed after 10 attempts"
-            exit 1
-          fi
-
       - name: backend api
         run: |
           success=false
-          for i in {1..10}; do
+          for i in {1..20}; do
             if curl -f http://localhost:8081; then
               success=true
               break
             else
-              sleep 10
+              sleep 20
             fi
           done
           
@@ -150,12 +137,29 @@ jobs:
       - name: swagger-ui
         run: |
           success=false
-          for i in {1..10}; do
+          for i in {1..20}; do
             if curl -f http://localhost:8081/swagger-ui/index.html#/user-controller/register; then
               success=true
               break
             else
-              sleep 10
+              sleep 20
+            fi
+          done
+          
+          if [ "$success" = false ]; then
+            echo "Curl failed after 10 attempts"
+            exit 1
+          fi
+
+      - name: frontend service
+        run: |
+          success=false
+          for i in {1..20}; do
+            if curl -f http://localhost:4201; then
+              success=true
+              break
+            else
+              sleep 20
             fi
           done
           
